"""Build the Atlas finalized-schedule PDF using ReportLab."""
from io import BytesIO
from datetime import datetime
from typing import List

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white
from reportlab.pdfgen import canvas


GOLD = HexColor("#FFC300")
GOLD_LIGHT = HexColor("#FFD84D")
CREAM = HexColor("#FDFCF5")
INK = HexColor("#111111")
MUTED = HexColor("#6b6b6b")
BORDER = HexColor("#e2dfd3")


def build_schedule_pdf(
    registered: List[dict],
    student_name: str = "UMBC Student",
    major: str = "Computer Science",
    term: str = "Fall 2026",
) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    W, H = LETTER

    # ─── Gold header band ─────────────────────────────────────
    c.setFillColor(GOLD)
    c.rect(0, H - 1.2 * inch, W, 1.2 * inch, fill=1, stroke=0)

    # Wordmark
    c.setFillColor(black)
    c.setFont("Helvetica-Bold", 28)
    c.drawString(0.6 * inch, H - 0.75 * inch, "ATLAS")
    c.setFont("Helvetica", 10)
    c.drawString(0.6 * inch, H - 0.95 * inch, "UMBC COEIT  ·  Registration Co-Pilot")

    # Right-aligned term
    c.setFont("Helvetica-Bold", 14)
    c.drawRightString(W - 0.6 * inch, H - 0.75 * inch, term.upper())
    c.setFont("Helvetica", 9)
    c.drawRightString(
        W - 0.6 * inch,
        H - 0.95 * inch,
        f"Generated {datetime.now().strftime('%b %-d, %Y · %-I:%M %p')}",
    )

    # ─── Student block ─────────────────────────────────────────
    y = H - 1.7 * inch
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(0.6 * inch, y, student_name)
    c.setFont("Helvetica", 11)
    c.setFillColor(MUTED)
    c.drawString(0.6 * inch, y - 0.22 * inch, f"{major}  ·  {term} Plan")

    # ─── Divider ───────────────────────────────────────────────
    y -= 0.55 * inch
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.75)
    c.line(0.6 * inch, y, W - 0.6 * inch, y)

    # ─── Courses heading ───────────────────────────────────────
    y -= 0.35 * inch
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.6 * inch, y, f"Planned Courses ({len(registered)})")

    # Column header
    y -= 0.28 * inch
    c.setFillColor(MUTED)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(0.6 * inch, y, "COURSE")
    c.drawString(2.0 * inch, y, "SECTION")
    c.drawString(3.1 * inch, y, "INSTRUCTOR")
    c.drawRightString(W - 0.6 * inch, y, "STATUS")

    y -= 0.12 * inch
    c.setStrokeColor(BORDER)
    c.line(0.6 * inch, y, W - 0.6 * inch, y)

    # ─── Course rows ───────────────────────────────────────────
    y -= 0.28 * inch
    row_h = 0.52 * inch
    for i, r in enumerate(registered):
        # Zebra stripe
        if i % 2 == 0:
            c.setFillColor(CREAM)
            c.rect(0.55 * inch, y - 0.16 * inch, W - 1.1 * inch, row_h - 0.04 * inch,
                   fill=1, stroke=0)

        # Left gold bar
        c.setFillColor(GOLD)
        c.rect(0.55 * inch, y - 0.16 * inch, 0.05 * inch, row_h - 0.04 * inch,
               fill=1, stroke=0)

        # Course code
        c.setFillColor(INK)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(0.75 * inch, y, r.get("course", "—"))

        # Section
        c.setFont("Helvetica", 11)
        c.setFillColor(INK)
        c.drawString(2.0 * inch, y, r.get("section", "—"))

        # Instructor
        c.setFont("Helvetica", 11)
        c.drawString(3.1 * inch, y, r.get("instructor", "—"))

        # Status pill — PLANNED (blue) for the upcoming term
        status = f"PLANNED · {term.upper()}"
        pill_w = 1.5 * inch
        pill_x = W - 0.6 * inch - pill_w
        c.setFillColor(HexColor("#1e40af"))
        c.roundRect(pill_x, y - 0.05 * inch, pill_w, 0.22 * inch, 0.11 * inch,
                    fill=1, stroke=0)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(pill_x + pill_w / 2, y + 0.02 * inch, status)

        y -= row_h

    # ─── Footer note ───────────────────────────────────────────
    y = 1.1 * inch
    c.setStrokeColor(BORDER)
    c.line(0.6 * inch, y + 0.3 * inch, W - 0.6 * inch, y + 0.3 * inch)

    c.setFillColor(MUTED)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(
        0.6 * inch,
        y,
        "Generated by Atlas — the UMBC COEIT registration co-pilot.",
    )
    c.setFont("Helvetica", 8)
    c.drawString(
        0.6 * inch,
        y - 0.18 * inch,
        "Instructor picks are based on GritView ratings and official UMBC grade distributions.",
    )

    # Gold footer accent
    c.setFillColor(GOLD)
    c.rect(0, 0, W, 0.12 * inch, fill=1, stroke=0)

    c.showPage()
    c.save()
    return buf.getvalue()
